version: '3.8'
name: reactivities

services:
  # ASP.NET Core Application
  web:
    image: reactivities:latest
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Reactivities;User Id=postgres;Password=admin;Include Error Detail=true
      - TokenKey=Yh2k7QSu4l8CZg5p6X3Pna9L0Miy4D3Bvt0JVr87UcOj69Kqw5R2Nmf4FWs03Hdx
      - Facebook__AppId=487386143777579
      - Facebook__AppSecret=9f6fbed4713bedbefde06c2eb3abfaa3
      - SendInBlue_ApiKey=123
    depends_on:
      - db

  # PostgreSQL Database
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=Reactivities
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Volumes for persistent PostgreSQL data
volumes:
  postgres-data:
